name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run linting
      run: poetry run ruff check --fix 

    - name: Run type-checking
      run: poetry run mypy limonata

    - name: Formatting
      run: poetry run ruff format

    - name: Check dependency updates
      run: poetry update

    - name: Build Sphinx documentation
      run: |
        cd docs
        poetry run sphinx-apidoc -o source/ ../limonata
        poetry run make html


