name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "${HOME}/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run linting
      run: poetry run ruff check --fix 

    - name: Run type-checking
      run: poetry run mypy limonata

    - name: Formatting
      run: poetry run ruff format

    - name: Check dependency updates
      run: poetry update

    - name: Build Sphinx documentation
      run: |
        cd docs
        poetry run sphinx-apidoc -o source/ ../limonata
        poetry run make html

    - name: Get Commit Author Email
      id: get_author
      run: |
        COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
        echo "COMMIT_EMAIL=$COMMIT_EMAIL" >> $GITHUB_ENV

    - name: Commit and Push changes
      run: |
        git config --local user.email "${{ env.COMMIT_EMAIL }}"
        git config --local user.name "${{ github.actor }}"  # Use the actor (username) for the commit
        git add .
        git commit -m "Apply formatting and linting fixes" || echo "No changes to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
